apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
    service: demo-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        version: v1
    spec:
      containers:
      - name: demo-app
        image: nginx:alpine
        ports:
        - containerPort: 8080
        env:
        - name: NGINX_PORT
          value: "8080"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        
        location / {
            return 200 "Hello from Demo App!\n";
            add_header Content-Type text/plain;
        }
        
        location /api/v1/data {
            return 200 "API Data Endpoint - This is rate limited!\n";
            add_header Content-Type text/plain;
        }
        
        location /api/v1/info {
            return 200 "API Info Endpoint - Less restricted\n";
            add_header Content-Type text/plain;
        }
    }
